### ISSUE TITLE
Garmin fenix 6 pro

### ISSUE THREAD

**Issue by arnaudlopez** [robayris/robayris.github.io#2]
Hi Rob, 
Can you consider to compile In The Zone for garmin fenix 6 pro ?
Great job by the way!
thanks

**Comment by robayris** [comment]
Hi Arnaud,

Thanks for reaching out.  Unfortunately, I can’t port ITZ to the fenix6 because the fenix6 screen size and resolution are just too small.  It works on the Epix2 because of the high resolution screen.
Sorry about that.  Two of my other apps TrainingPower and TrainingHR work on the Fenix6 though...

Cheers,
Rob.
